import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";
const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`)
];

const pluginContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external,
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod
});

const cliContext = await esbuild.context({
  banner: { js: "#!/usr/bin/env node" },
  entryPoints: ["src/cli/index.ts"],
  bundle: true,
  external: builtinModules,
  format: "esm",
  platform: "node",
  target: "node20",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "bin/dynamic-prompt.mjs",
  minify: prod
});

if (prod) {
  await pluginContext.rebuild();
  await cliContext.rebuild();
  process.exit(0);
} else {
  await pluginContext.watch();
  await cliContext.watch();
}
